version: '3.1'
services:
  mongodb:
    container_name: pokedex-mongo-db
    image: docker.io/mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: pokedex_db
    volumes:
      - "${HOME}/mongo_data:/data/db"
    ports:
      - "27017:27017"

  pokedex-service:
    container_name: poke-api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8081"