pokemon-external-api: https://pokeapi.co/api/v2/pokemon
server:
  port: 8081
  servlet:
    context-path: /pokedex/api/v1

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: admin
      password: admin
      database: pokedex
